app.controller('schools', ['$scope', function ($scope) {

	$scope.selectedSchools = "Abdul Gusau Polytechnic";
	
	$scope.schools = [
"Abdul Gusau Polytechnic",
"Abia State University",
"Abraham Adesanya Polytechnic",
"Abubakar Tafari Ali Polytechnic",
"Abubakar Tafawa Balewa University",
"Abubakar Tatari Ali Polytechnic Bauchi",
"Achievers University",
"Adamawa State Polytechnic",
"Adekunle Ajasin University",
"Adekunle Ajasin University, Akungba-Akoko",
"Afe Babalola University",
"Afe Babalola University, Ado Ekiti",
"Ahmadu Bello University",
"Ajayi Crowther University",
"Akanu Ibiam Federal Polytechnic",
"Akperan Orshi College of Agriculture",
"Akwa Ibom State Polytechnic",
"Akwa Ibom State University (formerly Akwa Ibom State University of Science and Technology)",
"Akwa-Ibom College of Agriculture",
"Al-Hikmah University",
"Allover Central Polytechnic",
"Ambrose Alli University",
"American University of Nigeria",
"Anambra State University formerly Anambra State University Of Science And Technology",
"Auchi Polytechnic",
"Audu Bako School of Agriculture",
"Babcock University",
"Bauchi State University, Gadau, Bauchi State",
"Bayelsa State College of Arts and Science",
"Bayero University",
"Bells University of Technology",
"Benson Idahosa University",
"Benue State Polytechnic",
"Benue State University",
"Bestower International University, Benin Republic, Cotonou",
"Borno College of Agriculture",
"Bowen University",
"Bukar Abba Ibrahim University",
"Caleb University",
"Caritas University",
"Caritas University, Enugu",
"CETEP City University",
"City University",
"City University of Technology",
"City University, Yaba, Lagos State",
"Citygate University, Ibadan",
"College of Agriculture and Animal Science",
"College of Agriculture, Jalingo",
"College of Agriculture, Kabba",
"College of Agriculture, Lafia",
"College of Agriculture, Zuru",
"Covenant University",
"Crawford University",
"Crescent University",
"Cross River University of Technology",
"Cross River University of Technology, Calabar",
"Crownhill University, Ilorin, Kwara State",
"Delta State College of Agriculture",
"Delta State Polytechnic (three institutions)",
"Delta State University, Abraka",
"Divine Polytechnic, Mkpani",
"Dorben Polytechnic",
"Eastern Polytechnic",
"Ebonyi State University",
"ECWA Bingham University",
"Edo State Polytechnic Usen",
"Ekwenugo Okeke Polytechnic",
"Elizade University",
"Enugu State University of Science and Technology, Enugu",
"Evangel University, Akaeze",
"Federal College of Agriculture, Ishiagu",
"Federal College of Animal Health & Production Technology",
"Federal College of Animal Health and Production Technology, Ibadan",
"Federal College of Animal Health and Production Technology, Vom",
"Federal College of Chemical and Leather and Technology",
"Federal College of Education, Pankshin",
"Federal College of Fisheries and Marine Technology",
"Federal College of Forestry Mechanisation",
"Federal College of Forestry, Ibadan",
"Federal College of Forestry. Jos",
"Federal College of Fresh Water Fisheries Technology",
"Federal College of Land Resources Technology, Kuru",
"Federal College of Land Resources Technology, Owerri",
"Federal College of Wildlife Management",
"Federal Polytechnic Ekowe Bayelsa State",
"Federal Polytechnic, Ado-Ekiti",
"Federal Polytechnic, Bauchi",
"Federal Polytechnic, Bida",
"Federal Polytechnic, Birnin-Kebbi",
"Federal Polytechnic, Damaturu",
"Federal Polytechnic, Ede",
"Federal Polytechnic, Idah",
"Federal Polytechnic, Ilaro",
"Federal Polytechnic, Mubi",
"Federal Polytechnic, Namoda",
"Federal Polytechnic, Nassarawa",
"Federal Polytechnic, Nekede",
"Federal Polytechnic, Offa",
"Federal Polytechnic, Oko",
"Federal School of Dental Technology & Therapy",
"federal school of statistics Manchok",
"Federal University Gashua, Yobe State",
"Federal University Gusau, Zamfara State",
"Federal University Ndufe Alike, Ikwo",
"Federal University of Agriculture, Abeokuta",
"Federal University of Dutse (FUD)",
"Federal University of Petroleum Resource Effurun",
"Federal University of Technology Akure",
"Federal University of Technology Minna",
"Federal University of Technology Owerri",
"Federal University, Birnin Kebbi, Kebbi State",
"Federal University, Dutsin-Ma",
"Foundation College of Technology",
"Fountain University, Osogbo",
"Gateway Polytechnic Saapade",
"Godfrey Okoye University",
"Gombe State University of Science and Technology, Kumo",
"Gombe State University, Gombe",
"Grace Polytechnic",
"Gregory University",
"Hassan Usman Katsina Polytechnic",
"Heritage Polytechnic",
"Hussaini Adamu Federal Polytechnic",
"Hussani Adamu Polytechnic",
"Ibrahim Babangida College of Agriculture",
"Ibrahim Babangida University, Lapai",
"Ibrahim Badamasi Babangida University, Niger State, Lapai",
"Igbajo Polytechnic, Igbajo",
"Igbinedion University",
"Ignatius Ajuru University of Education (Rivers State University of Education), Port Harcourt",
"Imo State Polytechnic",
"Imo State Technological Skills Acquisition Center",
"Imo State University, Owerri",
"Institute of Management and Technology, Enugu",
"Institute of Management Technology, Enugu",
"Interlink Polytechnic",
"Joseph Ayo Babalola University",
"Joseph Ayo Babalola University, Ikeji-Arakeji",
"Kaduna Polytechnic",
"Kaduna State University, Kaduna Kaduna State",
"Kano State Polytechnic",
"Kano State University of Science and Technology, Wudil",
"Kebbi State Polytechnic",
"Kebbi State University of Technology Aliero",
"Kings Polytechnic",
"Kogi State Polytechnic",
"Kogi State University, Ayigba, Kogi State",
"Koladaisi University",
"Koladaisi University Ibadan, Oyo State",
"Koladaisi University, Ibadan, Oyo State",
"Kwara State Polytechnic",
"Kwara State University, Malete, Kwara State",
"Ladoke Akintola University of Technology, Ogbomoso",
"Lagos Business School, Lagos",
"Lagos City Polytechnic",
"Lagos State Polytechnic",
"Lagos State University",
"Landmark University",
"Lead City University, Ibadan",
"Madonna University (Ihiala), Okija",
"Mai Idris Alooma Polytechnic",
"Maritime Academy of Nigeria",
"Marvic Polytechnic",
"Maurid Institute of Management & Technology, Nasarawa",
"Michael and Cecilia Ibru University",
"Michael and Cecilia Ibru University, Agbara-Otor, Ughelli North, Delta State",
"Michael Okpara Federal University of Agriculture, Umudike",
"Modibbo Adama University of Technology, Yola",
"Mohammed Abdullahi Wase Polytechnic",
"Moshood Abiola Polytechnic",
"Mountain Top University, Ogun State[2]",
"Nasarawa State Polytechnic",
"Nasarawa State University, Keffi",
"National Open University of Nigeria",
"National Open University of Nigeria, Lagos",
"Niger Delta University, Wilberforce Island, Bayelsa State",
"Niger State College of Agriculture",
"Niger State Polytechnic",
"Nigerian Army University Biu (NAUB)[3]",
"Nigerian College of Aviation Technology",
"Nigerian Defence Academy, Kaduna",
"Nigerian Turkish Nile University",
"Nnamdi Azikiwe University, Awka",
"Northwest University, Kano",
"Novena University, Ogume, Delta State",
"Nuhu Bamalli Polytechnic",
"Obafemi Awolowo University, Ile Ife",
"Obong University, Obong Ntak, Akwa Ibom",
"Oduduwa University",
"Oduduwa University, Ipetumodu, Osun State",
"Ogun State College of Health Technology",
"Olabisi Onabanjo University, Ago-Iwoye, Ogun State",
"Ondo State University of Science and Technology, Okitipupa",
"Osun State College of Technology",
"Osun State Polytechnic",
"Osun State University, Osogbo",
"Our Saviour Institute of Science and Technology",
"Pan-Atlantic University, Lagos",
"Paul University, Awka Anambra",
"Petroleum Training Institute",
"Plateau State College of Agriculture",
"Plateau State Polytechnic",
"Polytechnic Ile-Ife",
"Port Harcourt Polytechnic",
"Ramat Polytechnic",
"Redeemer's University Nigeria",
"Redeemer's University, Off, Gbongan ? Oshogbo Rd, Ede",
"Renaissance University, Agbani",
"Rhema University, Aba Abia State",
"Ritman University, Ikot Ekpene, Akwa Ibom State",
"Rivers State Polytechnic",
"Rivers State University, Port Harcourt",
"Ronik Polytechnic",
"Rufus Giwa Polytechnic",
"Salem University, Lokoja Kogi State",
"Samaru College of Agriculture",
"Samuel Adegboyega University, Ogwa Edo State",
"School of Agriculture, Ikorodu",
"Shaka Polytechnic",
"Sokoto State University, Sokoto",
"Southern Nigeria Institute of Innovative Technology (SNIITPOLY)",
"Sule Lamido University, Kaffin Hausa, Jigawa State",
"Tai Solarin University of Education, Ijebu-Ode, Ogun State",
"Taraba State University",
"Temple Gate Polytechnic",
"The Kings Poly, Shaki, Oyo",
"The Oke-Ogun Polytechnic, Saki",
"The Polytechnic, Calabar",
"The Polytechnic, Ibadan",
"The UA College of Science and Technology , Isuofia",
"The University on Idemili, Alor, Anambra State",
"Tower Polytechnic, Ibadan",
"Umaru Musa Yar'adua University Katsina",
"University of Abuja, Gwagwalada",
"University of Ado Ekiti, Ado Ekiti",
"University of Africa(Toru-Orua),Bayelsa State",
"University of Agriculture, Abeokuta, Abeokuta",
"University of Agriculture, Makurdi, Makurdi, Benue State",
"University of Benin",
"University of Calabar",
"University of Ibadan",
"University of Ibadan, Ibadan",
"University of Ilorin, Ilorin",
"University of Jos, Jos",
"University of Lagos",
"University of Maiduguri, Maiduguri",
"University of Mkar, Mkar-Gboko, Benue State",
"University of Nigeria, Nsukka",
"University of Port Harcourt",
"University of Uyo, Uyo, Akwa Ibom State",
"Usman Dan Fodio University, Sokoto, Sokoto State",
"Veritas University (Catholic University of Nigeria) Abuja",
"Wavecrest College of Hospitality",
"Wesley University, Ondo",
"Western Delta University, Oghara, Delta State",
"Wolex Polytechnic",
"Yaba College of Technology",
"Yaba College of Technology, Yaba, Lagos State, Nigeria"
        	]

$scope.Terminals =  [
		  {
		  	"TerminalId": 4,
		  	"TerminalName": "Edo => Auchi",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": "08130469949",
		  	"Latitude": 7.05,
		  	"Longitude": 6.27,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 3,
		  	"StateName": "Edo",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 5,
		  	"TerminalName": "Edo => Benin (Uselu)",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.37732363,
		  	"Longitude": 5.613208,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 3,
		  	"StateName": "Edo",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 6,
		  	"TerminalName": "Lagos => Iyana Ipaja",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.617549,
		  	"Longitude": 3.303139,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 7,
		  	"TerminalName": "Lagos => Ajah",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.469876,
		  	"Longitude": 3.579997,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 8,
		  	"TerminalName": "Abia => Umuahia",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 5.052626,
		  	"Longitude": 7.88301,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 5,
		  	"StateName": "Abia",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 9,
		  	"TerminalName": "Abia => Aba",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 5.111965,
		  	"Longitude": 7.370482,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 5,
		  	"StateName": "Abia",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 10,
		  	"TerminalName": "Akwa Ibom => Uyo",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 5.052707,
		  	"Longitude": 7.883109,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 6,
		  	"StateName": "Akwa Ibom",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 11,
		  	"TerminalName": "Anambra => Awka",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.223521,
		  	"Longitude": 7.06723,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 7,
		  	"StateName": "Anambra",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 12,
		  	"TerminalName": "Bayelsa => Yenagoa",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 4.934752,
		  	"Longitude": 6.309846,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 8,
		  	"StateName": "Bayelsa",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 13,
		  	"TerminalName": "Delta(South-East) => Asaba (Onitsha)",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.138825,
		  	"Longitude": 6.750893,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 15,
		  	"StateName": "Delta(South-East)",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 14,
		  	"TerminalName": "Edo => Benin (Akpakpava)",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.341849,
		  	"Longitude": 5.634196,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 3,
		  	"StateName": "Edo",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 15,
		  	"TerminalName": "Edo => Ekpoma",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.377928,
		  	"Longitude": 5.613375,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 3,
		  	"StateName": "Edo",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 17,
		  	"TerminalName": "Enugu => Enugu",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.436332,
		  	"Longitude": 7.490581,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 10,
		  	"StateName": "Enugu",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 18,
		  	"TerminalName": "FCT Abuja => Mararaba",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 9.029498,
		  	"Longitude": 7.585855,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 4,
		  	"StateName": "FCT Abuja",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 19,
		  	"TerminalName": "FCT Abuja => Zuba",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 9.090496,
		  	"Longitude": 7.214938,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 4,
		  	"StateName": "FCT Abuja",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 20,
		  	"TerminalName": "FCT Abuja => Kubwa",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 9.148915,
		  	"Longitude": 7.325553,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 4,
		  	"StateName": "FCT Abuja",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 21,
		  	"TerminalName": "FCT Abuja => Utako",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 9.065255,
		  	"Longitude": 7.438164,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 4,
		  	"StateName": "FCT Abuja",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 22,
		  	"TerminalName": "Imo => Owerri",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": "08090216366,08113953329",
		  	"Latitude": 5.478162,
		  	"Longitude": 7.046396,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 11,
		  	"StateName": "Imo",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 23,
		  	"TerminalName": "Imo => Orlu",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 5.482407,
		  	"Longitude": 7.032872,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 11,
		  	"StateName": "Imo",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 24,
		  	"TerminalName": "Kaduna => Kaduna",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 10.59,
		  	"Longitude": 7.44,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 12,
		  	"StateName": "Kaduna",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 25,
		  	"TerminalName": "Lagos => Festac (mazamaza)",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": "08038061658,08035000610",
		  	"Latitude": 6.462327,
		  	"Longitude": 3.301364,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 26,
		  	"TerminalName": "Lagos => Volks",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.459356,
		  	"Longitude": 3.212913,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 27,
		  	"TerminalName": "Lagos => Ikotun",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.550455,
		  	"Longitude": 3.26813,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 28,
		  	"TerminalName": "Lagos => Yaba",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.509781,
		  	"Longitude": 3.371619,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 29,
		  	"TerminalName": "Lagos => Jibowu",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.518806,
		  	"Longitude": 3.367547,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 30,
		  	"TerminalName": "Lagos => Oyingbo (Iddo)",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.47,
		  	"Longitude": 3.38,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 1,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 31,
		  	"TerminalName": "Plateau => Jos",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 9.931281,
		  	"Longitude": 8.876801,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 13,
		  	"StateName": "Plateau",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 32,
		  	"TerminalName": "Rivers => Port Harcourt",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": "07031195208",
		  	"Latitude": 4.84,
		  	"Longitude": 7.01,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 14,
		  	"StateName": "Rivers",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 33,
		  	"TerminalName": "Lagos => Old Ojo Road",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": "09087492062",
		  	"Latitude": 6.46259451,
		  	"Longitude": 3.29235458,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 34,
		  	"TerminalName": "Akwa Ibom => Calabar",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 1,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 6,
		  	"StateName": "Akwa Ibom",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 35,
		  	"TerminalName": "Delta(South-South) => Warri",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 5.547115,
		  	"Longitude": 5.780381,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 9,
		  	"StateName": "Delta(South-South)",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 37,
		  	"TerminalName": "FCT Abuja => Kubwa, Bwari Area Council Camp",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 4,
		  	"StateName": "FCT Abuja",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 38,
		  	"TerminalName": "Abia => Bende Local Government Area Camp",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 5,
		  	"StateName": "Abia",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 41,
		  	"TerminalName": "Delta(South-South) => Aniocha North L.G.A. Camp",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 9,
		  	"StateName": "Delta(South-South)",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 45,
		  	"TerminalName": "Kaduna => Kaduna – Abuja Road Camp",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 12,
		  	"StateName": "Kaduna",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 46,
		  	"TerminalName": "Plateau => Jakatai-Mangu Mangu LGA Camp",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "1900-01-01T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 13,
		  	"StateName": "Plateau",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 49,
		  	"TerminalName": "Lagos => Cele/Okota",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.50919676,
		  	"Longitude": 3.31616974,
		  	"IsNew": false,
		  	"TerminalStartDate": "2017-12-20T08:32:32.27",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 57,
		  	"TerminalName": "Lagos => AJAHBACKWARD",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "2018-07-09T12:33:28.8933333",
		  	"TerminalType": 1,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 59,
		  	"TerminalName": "Lagos => Head Office",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 6.428719,
		  	"Longitude": 3.468449,
		  	"IsNew": false,
		  	"TerminalStartDate": "2018-07-24T12:33:29.4533333",
		  	"TerminalType": 1,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 60,
		  	"TerminalName": "FCT Abuja => Madalla Zuba",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 9.090496,
		  	"Longitude": 7.214938,
		  	"IsNew": false,
		  	"TerminalStartDate": "2018-12-06T16:21:06.6933333",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 4,
		  	"StateName": "FCT Abuja",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 61,
		  	"TerminalName": "Lagos => Admiralty",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "2019-01-16T10:27:05.12",
		  	"TerminalType": 1,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  },
		  {
		  	"TerminalId": 63,
		  	"TerminalName": "Lagos => Akowonjo (Dopemu)",
		  	"TerminalCode": null,
		  	"TerminalImage": null,
		  	"TerminalAddress": null,
		  	"ContactPerson": null,
		  	"ContactPersonNo": null,
		  	"Latitude": 0,
		  	"Longitude": 0,
		  	"IsNew": false,
		  	"TerminalStartDate": "2019-05-16T00:00:00",
		  	"TerminalType": 0,
		  	"BookingType": 0,
		  	"TicketRemovalOtp": null,
		  	"TicketRemovalOtpIsUsed": false,
		  	"DiscountOtp": null,
		  	"DiscountOtpIsUsed": false,
		  	"StateId": 2,
		  	"StateName": "Lagos",
		  	"RouteId": 0
		  }
	];

$scope.Departments = [
		{
			"DepartmentId": 15,
			"DepartmentName": "Operations",
			"DateCreated": "2017-06-01T11:24:25.4",
			"DateModified": "2017-06-01T11:24:25.4",
			"IsDeleted": false
		},
		{
			"DepartmentId": 14,
			"DepartmentName": "Terminal Experience Officers",
			"DateCreated": "2017-06-01T11:24:14.777",
			"DateModified": "2017-06-01T11:24:14.777",
			"IsDeleted": false
		},
		{
			"DepartmentId": 4,
			"DepartmentName": "Innovation",
			"DateCreated": "2017-04-20T09:45:42.107",
			"DateModified": "2017-04-20T14:17:48.783",
			"IsDeleted": false
		},
		{
			"DepartmentId": 12,
			"DepartmentName": "Workshop",
			"DateCreated": "2017-04-20T09:47:44.277",
			"DateModified": "2017-04-20T09:47:44.277",
			"IsDeleted": false
		},
		{
			"DepartmentId": 11,
			"DepartmentName": "Inventory",
			"DateCreated": "2017-04-20T09:47:20.3",
			"DateModified": "2017-04-20T09:47:20.3",
			"IsDeleted": false
		},
		{
			"DepartmentId": 10,
			"DepartmentName": "OST",
			"DateCreated": "2017-04-20T09:47:09.69",
			"DateModified": "2017-04-20T09:47:09.69",
			"IsDeleted": false
		},
		{
			"DepartmentId": 9,
			"DepartmentName": "Fleet",
			"DateCreated": "2017-04-20T09:47:01.927",
			"DateModified": "2017-04-20T09:47:01.927",
			"IsDeleted": false
		},
		{
			"DepartmentId": 8,
			"DepartmentName": "Training",
			"DateCreated": "2017-04-20T09:46:36.5",
			"DateModified": "2017-04-20T09:46:36.5",
			"IsDeleted": false
		},
		{
			"DepartmentId": 7,
			"DepartmentName": "Finance",
			"DateCreated": "2017-04-20T09:46:12.373",
			"DateModified": "2017-04-20T09:46:12.373",
			"IsDeleted": false
		},
		{
			"DepartmentId": 6,
			"DepartmentName": "Account",
			"DateCreated": "2017-04-20T09:46:03.057",
			"DateModified": "2017-04-20T09:46:03.057",
			"IsDeleted": false
		},
		{
			"DepartmentId": 5,
			"DepartmentName": "Human Capital Development",
			"DateCreated": "2017-04-20T09:45:54.363",
			"DateModified": "2017-04-20T09:45:54.363",
			"IsDeleted": false
		},
		{
			"DepartmentId": 3,
			"DepartmentName": "Marketing/Innovation",
			"DateCreated": "2017-04-20T09:45:31.603",
			"DateModified": "2017-04-20T09:45:31.603",
			"IsDeleted": false
		},
		{
			"DepartmentId": 2,
			"DepartmentName": "Information Technology",
			"DateCreated": "2017-04-20T09:45:13.487",
			"DateModified": "2017-04-20T09:45:13.487",
			"IsDeleted": false
		},
		{
			"DepartmentId": 1,
			"DepartmentName": "Customer Service",
			"DateCreated": "2017-03-26T21:01:49.117",
			"DateModified": "2017-04-20T09:44:54.703",
			"IsDeleted": false
		},
		{
			"DepartmentId": 13,
			"DepartmentName": "Admin",
			"DateCreated": "2017-04-12T00:16:38.243",
			"DateModified": "2017-04-12T00:16:38.243",
			"IsDeleted": false
		}
];

        }]); 
